title: KT Hack 2020
description: Official web page of KT Hack 2020
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
basvuru_linki: https://docs.google.com/forms/d/e/1FAIpQLSeSTQB8FR26KZM0n12MCiQXoUZH1JD8IIiFLuG5FXue8Ab1Jg/viewform
